import { FolderOpen, Moon, RotateCcw, Sun } from 'lucide-react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import type { AppSettings, Condominio } from '../types/domain'

export function Preferences({settings}:{settings:AppSettings}){
 const query=useQueryClient();const [draft,setDraft]=useState(settings);const [newCategory,setNewCategory]=useState('');const {data:all=[]}=useQuery({queryKey:['condominios','all'],queryFn:()=>window.tud.condominios.list(true)});const {data:version='…'}=useQuery({queryKey:['app-version'],queryFn:()=>window.tud.app.version()});const archived=all.filter((x:Condominio)=>x.arquivado)
 useEffect(()=>setDraft(settings),[settings]);const update=async(patch:Partial<AppSettings>)=>{const next=await window.tud.settings.set(patch);setDraft(next);await query.invalidateQueries({queryKey:['settings']})}
 const addCategory=()=>{const name=newCategory.trim();if(!name||draft.categories.some(x=>x.toLowerCase()===name.toLowerCase()))return;const categories=[...draft.categories,name];setNewCategory('');update({categories})}
 return <div className="page preferences"><span className="eyebrow">Configuração</span><h1 className="display md"><em>Preferências</em></h1><p className="support">Ajuste o ritmo, os dados e o comportamento do TUD no Windows.</p>
 <section className="pref-section"><h2>Aparência</h2><p className="muted">Escolha o tema e a densidade mais confortáveis para trabalhar.</p><div className="pref-row"><span>Tema</span><div className="segmented"><button className={draft.theme==='light'?'active':''} onClick={()=>update({theme:'light'})}><Sun size={15}/> Claro</button><button className={draft.theme==='dark'?'active':''} onClick={()=>update({theme:'dark'})}><Moon size={15}/> Escuro</button></div></div><div className="pref-row"><span>Densidade</span><div className="segmented"><button className={draft.density==='comfortable'?'active':''} onClick={()=>update({density:'comfortable'})}>Confortável</button><button className={draft.density==='compact'?'active':''} onClick={()=>update({density:'compact'})}>Compacto</button></div></div></section>
 <section className="pref-section"><h2>Animações</h2><div className="pref-row"><span>Nível de animação</span><div className="segmented">{[['full','Completas'],['reduced','Reduzidas'],['off','Desligadas']].map(([value,label])=><button key={value} className={draft.animation===value?'active':''} onClick={()=>update({animation:value as any})}>{label}</button>)}</div></div><Toggle label="Efeitos de fundo" value={draft.backgroundEffects} onChange={v=>update({backgroundEffects:v})}/><Toggle label="Abertura animada" value={draft.splash} onChange={v=>update({splash:v})}/><Toggle label="Partículas ao registrar" value={draft.particles} onChange={v=>update({particles:v})}/></section>
 <section className="pref-section"><h2>Categorias</h2><p className="muted">Categorias usadas nos formulários e filtros.</p><div className="category-list">{draft.categories.map(name=><span className="chip" key={name}>{name}<button className="icon-button" style={{width:22,height:22}} onClick={()=>update({categories:draft.categories.filter(x=>x!==name)})}>×</button></span>)}</div><div className="category-edit"><input className="quick-input" value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Nova categoria" onKeyDown={e=>{if(e.key==='Enter')addCategory()}}/><button className="secondary" onClick={addCategory}>Adicionar</button></div></section>
 <section className="pref-section"><h2>Dados</h2><p className="muted">Pasta fixa: Documentos\TUD Dados. Para restaurar após formatar o computador, recoloque essa pasta no mesmo local antes de abrir o TUD.</p><div className="intro-actions"><button className="secondary" onClick={()=>window.tud.backup.create(draft.backupFolder)}>Fazer backup agora</button><button className="secondary" onClick={()=>window.tud.backup.restore()}>Restaurar backup</button><button className="secondary" onClick={()=>window.tud.export.csv()}>Exportar CSV</button><button className="secondary" onClick={()=>window.tud.app.openDataFolder()}><FolderOpen size={16}/> Abrir pasta de dados</button></div><Toggle label="Backup automático ao fechar" value={draft.autoBackup} onChange={v=>update({autoBackup:v})}/>{archived.length>0&&<><h2 style={{marginTop:28}}>Condomínios arquivados</h2>{archived.map((x:Condominio)=><div className="pref-row" key={x.id}><span>{x.nome}</span><button className="secondary" onClick={async()=>{await window.tud.condominios.restore(x.id);await query.invalidateQueries()}}><RotateCcw size={15}/> Restaurar</button></div>)}</>}</section>
 <section className="pref-section"><h2>Sistema</h2><Toggle label="Iniciar com o Windows" value={draft.startWithWindows} onChange={v=>update({startWithWindows:v})}/><Toggle label="Atalho global Ctrl+Alt+T" value={draft.globalShortcut} onChange={v=>update({globalShortcut:v})}/><Toggle label="Usar ícone na bandeja" value={draft.tray} onChange={v=>update({tray:v})}/><div className="pref-row"><span>Ao fechar</span><div className="segmented"><button className={draft.closeBehavior==='quit'?'active':''} onClick={()=>update({closeBehavior:'quit'})}>Sair</button><button className={draft.closeBehavior==='tray'?'active':''} onClick={()=>update({closeBehavior:'tray',tray:true})}>Minimizar para bandeja</button></div></div><p className="muted">Mudanças de integração com o Windows entram em vigor na próxima abertura.</p></section>
 <section className="pref-section"><h2>Sobre</h2><p className="muted">TUD — Tracking u Down · versão {version}<br/>100% local. Sem conta, nuvem ou telemetria.</p></section></div>
}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="pref-row"><span>{label}</span><button className={`toggle ${value?'on':''}`} onClick={()=>onChange(!value)} role="switch" aria-checked={value}><i/></button></div>}
